### ISSUE TITLE
Tests on regular install rather than editable

### ISSUE THREAD

**Issue by guiwitz** [tlambert03/pyrepo-cookiecutter#11]
Hi @tlambert03 ,
I'm using your great cookiecutter and recently encountered an issue with how tests are run. In the CI action, the installation is done in editable mode here https://github.com/tlambert03/pyrepo-cookiecutter/blob/f138f277524e5f1a7f3abaec2aa2879190711baf/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/ci.yml#L49
The problem I encountered is the following: I made a package needing some non python data to work. Those data are present in the repository. However I made a mistake in the package configuration / data location, with the consequence that those data were not present in the wheel build. So the package would fail after a regular install, but not in editable mode because then the "local" version of the data is used.

So my question is: is there an advantage to run the tests in editable mode? My guess is that if tests were run on the regular version, this sort of problem would trigger an error and so that would be beneficial? I'm curious to know what you think!

**Comment by tlambert03** [comment]
hey @guiwitz, yeah that's probably a better default.  I *have* run into some cases before where for some reason I needed an editable install, but honestly I can't remember why anymore, and on the surface, it looks less correct.  I'll update the cookiecutter.

that said: this is why I include the check-manifest test in the standard version:

https://github.com/tlambert03/pyrepo-cookiecutter/blob/f138f277524e5f1a7f3abaec2aa2879190711baf/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/ci.yml#L15-L19

did you run the "simple" version and does it lack that test?

**Comment by guiwitz** [comment]
Thanks for the hint. No indeed that ```check-manifest``` test is not present in the simple version. But I anyway didn't have the data added to a ```MANIFEST.in``` file but rather tried to include them with one of the include/exclude options available via the ```tool.hatch.build.targets.wheel``` section in ```pyproject.toml``` (the documentation is still a bit confusing so I ended up just moving the data directly in the package and not using hatch for this). So in this case, I'm not sure this test would have worked.

**Comment by tlambert03** [comment]
Despite the name, Check-manifest doesn't depend on manifest.in (which is sort of an antiquated file anyway).  It just checks to make sure that all your data files checked into source either get into the package or are explicitly ignored.  Works great with hatch too.  I think it's a very valuable tool to add.  Curious what you see when you run it (you can do it locally too just to check)

**Comment by guiwitz** [comment]
So I tested it and I still think my edge-case wouldn't be covered here. I put a ```data``` folder inside the ```src``` folder (not in the module folder) and it is under vcs. In this case this ```data``` folder is present in the sdist distribution and therefore check-manifest doesn't complain. Also the tests on the editable install work. However if my hatch wheel configuration is incorrect (or missing) then this same ```data``` folder is missing in the wheel distribution. And in this case, only the test with a regular install triggers an error.

**Comment by tlambert03** [comment]
> However if my hatch wheel configuration is incorrect (or missing) then this same data folder is missing in the wheel distribution.

well that's certainly interesting!  can you point to the repo by chance? (just for my edification of what check-manifest can and cannot catch)

**Comment by guiwitz** [comment]
It's not impossible at all that I messed up with something. Here's the repo where I had issues: https://github.com/guiwitz/PyMicrofluidics. I made this package a long time ago, before I started learning how to do things in a more professional way (a lot thanks to you via napari actually!), and the issue appeared when I "modernized" the package.

Since the problem is fixed now, I made a specific branch which should demonstrate the issue: https://github.com/guiwitz/PyMicrofluidics/tree/check-manifest. When installed in ```-e``` mode this works, but not when installed in a regular way. ```check-manifest``` doesn't complain, the ```data``` folder is in the sdist but not in the wheel.

**Comment by tlambert03** [comment]
ohhh... cause you didn't put `src/data` inside of the `src/pymicrofluidics` folder!  Yeah I can definitely see that's a bit confusing/tricky to understand/explain (Technically, with that folder placement, you would have been going for the `data` folder to end up in the top level of `site-packages`?)

I definitely agree that just using a non-editable install is probably the best way to have caught that (and it also makes me wish that check-manifest could have caught that).  

thanks for sharing!

**Comment by tlambert03** [comment]
updated both main and simple branches.  thanks for reporting

**Comment by tlambert03** [comment]
aha! I found this comment in one of my repos:

```yaml
      - name: Build
        # -e seems necessary for coverage to work
        run: pip install -e .[test]
```

just wanted to note that here: pay attention to test coverage when not using editable installs.  In this case, it was a cython project, using a cython plugin to look at coverage for cythonized files (probably a special case).

**Comment by tlambert03** [comment]
... and one more detail.  

If you use 

```toml
[tool.coverage.run]
source = ["your_top_module"]
```

instead of 

```toml
[tool.coverage.run]
source = ["src"]
```

(or pass the name directly to the `--cov` argument)

then coverage should work for both editable and non-editable installs
